version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cqrs_db
    ports:
      - "6543:5432"  # Porta personalizada
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:5
    container_name: mongodb
    restart: always
    ports:
      - "37017:27017"  # Porta personalizada
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db  # Monta o volume para persistência de dados

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5673:5672"  # Porta para o cliente
      - "15673:15672"  # Porta para o painel de gerenciamento
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  app_flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python main.py
volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data:
