# Use a imagem base do Node.js
FROM node:20.17.0 AS build

# Defina o diretório de trabalho
WORKDIR /app

# Copie o package.json e o package-lock.json
COPY package*.json yarn.lock ./

# Instale as dependências
RUN yarn install

# Copie o restante do código da aplicação
COPY . .

# Construa a aplicação
RUN yarn build

# Exponha a porta que a aplicação irá rodar
EXPOSE 3001

# Comando para iniciar a aplicação
CMD ["yarn", "start"]
