name: Docker Publish

on:
  pull_request:
    types:
      - closed
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r ./produtos_service/requirements.txt

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run Backend Tests
      run: |
        pytest ./produtos_service/tests

  docker_build_and_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Docker Compose
      run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

    - name: Build Docker Images
      run: |
        export GITHUB_RUN_NUMBER=${{ github.run_number }}
        echo "GITHUB_RUN_NUMBER=${{ github.run_number }}"  
        docker-compose -f docker-compose.yaml build

    - name: Push Docker Images
      run: |
        docker-compose -f docker-compose.yaml push
