name: Gitflow with Pull Requests to Develop

on:
  # Evento para pull requests direcionadas à develop
  pull_request:
    branches:
      - develop

  # Evento para branches feature/*
  push:
    branches:
      - feature/*

jobs:
  ci-feature:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          echo "Running unit tests for feature branch"
          # Substituir com o comando real de testes
          pytest ./tests

      - name: Code Quality Check
        run: |
          echo "Running lint checks"
          # Substituir com o comando real de lint
          flake8 ./src

  ci-pr-develop:
    # Evento específico para PRs abertas contra a branch develop
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Integration Tests
        run: |
          echo "Running integration tests for pull request to develop"
          pytest ./integration_tests

      - name: Build Docker Images
        run: |
          echo "Building Docker images"
          docker-compose build

      - name: Deploy to Staging
        if: github.event.pull_request.merged == true
        run: |
          echo "Deploying to staging environment"
          docker-compose up -d
