name: Gitflow with Pull Requests

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - feature/*

jobs:
  ci-feature:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: |
          echo "Running unit tests for feature branch"
          # Comando de teste aqui
          pytest ./tests

      - name: Lint and Code Quality Check
        run: |
          echo "Running lint and quality checks"
          # Exemplo de lint
          flake8 ./src

  ci-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Integration Tests
        run: |
          echo "Running integration tests for pull request"
          # Comando de teste de integração aqui
          pytest ./integration_tests

      - name: Build Docker Images
        run: |
          echo "Building Docker images"
          docker-compose build

      - name: Deploy to Staging
        if: github.event.pull_request.merged == true
        run: |
          echo "Deploying to staging environment"
          docker-compose up -d
