name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r ./produtos_service/requirements.txt

    - name: Install pytest
      run: |
        pip install pytest

    - name: Run Backend Tests
      run: |
        pytest ./produtos_service/tests

  frontend_build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.17.0'

    - name: Install Frontend Dependencies
      run: |
        cd front-end
        npm install -g npm-force-resolutions
        npm run fix-deps

    - name: Build Frontend Application
      run: |
        cd front-end
        npm run build

  build:
    runs-on: ubuntu-latest
    needs: [test, frontend_build]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Images
      run: |
        export GITHUB_RUN_NUMBER=${{ github.run_number }}
        docker-compose -f docker-compose.yaml build

  push_back_end:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image for BackEnd
      run: |
        docker-compose -f docker-compose.yaml push app

  push_front_end:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image for FronEnd
      run: |
        docker-compose -f docker-compose.yaml push front-end